(add-to-load-path "/root")
(add-to-load-path "/root/collectiwise")
(add-to-load-path ".")
;(add-to-load-path "/root/opencog/opencog/learning/PatternMiner/")
;(add-to-load-path "/root/pln/tests/pln/rules/term/")
;(add-to-load-path "/root/pln/tests/pln/rules/")
;(add-to-load-path "/root/pln/tests/pln/rules/wip/")
(use-modules (ice-9 readline)) (activate-readline)
(add-to-load-path "/usr/local/share/opencog/scm")
(use-modules (opencog))
(use-modules (opencog query))
(use-modules (opencog exec))
(use-modules (opencog pln))
(use-modules (opencog rule-engine))
(load "/root/pln/tests/pln/rules/simple-assertions.scm")
(load "/root/pln/opencog/pln/rules/term/deduction.scm")
;(load "/root/pln/utilities.scm")
;(load "./opencog/opencog/learning/PatternMiner/testdatasmall.scm")
(load "/root/pln/opencog/pln/rules/wip/negation-introduction.scm")
(load-from-path "utility_functions.scm")
